# NUMPY

In [24]:
import numpy as np

In [25]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [26]:
type(arr)

numpy.ndarray

In [27]:
# to check the dimenstion
arr.ndim

1

In [28]:
# creating 2D array   List of list
arr2=np.array([[1,2,3],[1,3,5]])
print(arr2)

[[1 2 3]
 [1 3 5]]


In [29]:
#calculating size of array
arr2.size

6

In [30]:
# calculating shape
arr2.shape

(2, 3)

In [31]:
# identifing data type
arr2.dtype

dtype('int32')

In [32]:
# print 1 in matrics
a=np.ones((3,4))

print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
type(a)

numpy.ndarray

In [34]:
b=np.ones((3,4),dtype=int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [35]:
c=np.zeros((3,4),dtype=int)
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [36]:
c1=np.zeros((3,4),dtype=bool)
print(c1)

[[False False False False]
 [False False False False]
 [False False False False]]


In [37]:
c2=np.zeros((3,4),dtype=str)  #empty string express in notation mark
print(c2)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


# Arange()

In [38]:
arr=np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
ev_ar=np.arange(1,13,2)
print(ev_ar)

[ 1  3  5  7  9 11]


# linspace()

In [40]:

np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

# reshape

In [41]:
# change the dimenstion
arr1=arr.reshape(3,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# ravel

In [42]:
#conversion of two dimension to one dimention
arr1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten

In [43]:
# conversion of multidimention to one dimention
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose

In [44]:
arr1.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [45]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# Mathematic operation using numpy

In [46]:
ar=np.arange(1,10)
a=ar.reshape(3,3)
print(a)
ar1=np.arange(5,14)
b=ar1.reshape(3,3)
print(b)
sum=a+b
print("Addition of array")
print(sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Addition of array
[[ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [47]:
np.add(a,b)

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [49]:
np.subtract(a,b)

array([[-4, -4, -4],
       [-4, -4, -4],
       [-4, -4, -4]])

In [50]:
np.divide(a,b)

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.55555556, 0.6       ],
       [0.63636364, 0.66666667, 0.69230769]])

In [51]:
a*b

array([[  5,  12,  21],
       [ 32,  45,  60],
       [ 77,  96, 117]])

In [52]:
np.multiply(a,b)

array([[  5,  12,  21],
       [ 32,  45,  60],
       [ 77,  96, 117]])

In [53]:
a@b

array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])

In [57]:
ad=a.dot(b)
print(ad)

[[ 54  60  66]
 [126 141 156]
 [198 222 246]]


In [58]:
np.max(ad)

246

In [59]:
ad.argmax()

8

In [61]:
ad.max(axis=0)    #axis=0 for rows


array([198, 222, 246])

In [62]:
ad.max(axis=1)    # axis=1 foe coloum

array([ 66, 156, 246])

In [63]:
ad.min(axis=0)

array([54, 60, 66])

In [64]:
ad.argmin()

0

In [66]:
np.sum(a)

45

In [67]:
np.sum(a,axis=0)

array([12, 15, 18])

In [68]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [69]:
np.mean(a)

5.0

In [70]:
np.mean(b)

9.0

In [71]:
np.mean(ad)

141.0

In [72]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [73]:
np.std(b)

2.581988897471611

In [74]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])